### ISSUE TITLE
OLED code is missing

### ISSUE THREAD

**Issue by pipersw** [hallard/LibTeleinfo#11]
Bonjour,
Sur le Wifinfo, un connecteur est prévu pour un Oled I2C, et une case est prévue dans l'interface web pour l'activer.
Dans le code, rien n'apparait pour activer l'I2C et pour piloter l'Oled.
Peux-tu confirmer ?
Un SH1106 serait-il compatible ?
Une future évolution de code pour l'OLED est-elle prévue ?

Hi,
On the Wifinfo, a connector is provided for an I2C OLED, and a case is available in the configuration tab.
In the source code, nothing is provided for use the I2C and control the OLED.
Could you confirm ?
A SH1106 could be used ?
A future update for the OLED will be available ?

**Comment by hallard** [comment]
Oui je confirme, ce n'est pas géré, mais je viens de créer une PR pour ajouter la téléinfo à l'excellent Firmware [Tasmota](https://github.com/arendst/Tasmota). Celui ci supporte les OLED en natif (a voir comment afficher des données dessus)

Ma PR (basique pour le moment juste de l'affichage) est parfaitement fonctionnelle et elle est dispo [ici](https://github.com/arendst/Tasmota/pull/8695)
