### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by Vebryn** [hallard/LibTeleinfo#13]
Hi,

Great work! This library will ease my home automation! Your blog is also awesome, especially your teleinfo articles.

I would like to use this library. I'm wondering about initial setup like ssid and password in order to connect to frontend. Where are these parameters defined ?

Best regards.

**Comment by TionebErtahcnom** [comment]
#me too

i search how to add the esp in my network to access it.

**Comment by hallard** [comment]
Messieurs,

I made a PR to integrate Teleinfo into excellent  [Tasmota](https://github.com/arendst/Tasmota) firmware. The PR is located [here](https://github.com/arendst/Tasmota/pull/8695) and this all tasmota documentation is really great.
