### ISSUE TITLE
l'API Teleinfo dans jeedom à changé

### ISSUE THREAD

**Issue by Robokazou** [hallard/LibTeleinfo#15]
Bonjour,

**Merci** pour ce beau travail.

Cependant le développer du plugin Teleinfo dans Jeedom a visiblement changé les choses pour pousser les infos depuis wifinfo. Serai t'il possible de modifier la commande  jeedomPost() pour s'adapter à la nouvelle API du plugin teleinfo Jeedom.

Ou prévoir la compatibilité avec les 2 API si possible.

voir la doc du plugin:
https://nextdom.github.io/plugin-teleinfo/fr_FR/index#tocAnchor-1-14
API non compatible depuis la version 4.0.0 (28-02-2019) du plugin Jeedom.
voir changelog du plugin.
https://nextdom.github.io/plugin-teleinfo/fr_FR/changelog

Merci encore

**Comment by hallard** [comment]
Bonjour,

Je viens de créer une PR pour ajouter la téléinfo à l'excellent Firmware [Tasmota](https://github.com/arendst/Tasmota). Celui ci supporte un nombre impressionnant de devices, de fonctions et il est d'une stabilité exemplaire. Une fois intégré je verrais ce que je peux faire pour Jeedom.
