### ISSUE TITLE
Lien documentation télé-info

### ISSUE THREAD

**Issue by thibautsergent** [hallard/LibTeleinfo#17]
Bonjour,

Le lien vers la documentation télé-info renvoie vers un 404. 

Le nouveau lien est le suivant :
https://www.enedis.fr/sites/default/files/Enedis-NOI-CPT_02E.pdf

Une autre doc est disponible pour les compteurs linky : 
https://www.enedis.fr/sites/default/files/Enedis-NOI-CPT_54E.pdf

👍

**Comment by hallard** [comment]
Yeah, thanks for sharing, it's fixed
