### ISSUE TITLE
Teleinfo_DenkyD4 ne compile pas

### ISSUE THREAD

**Issue by FredM67** [hallard/LibTeleinfo#21]
Il semblerait qu'il manque certaines choses...
Entre autre, ne sont pas définis:
- _Mode_e
- TINFO_MODE_STANDARD
- TINFO_MODE_HISTORIQUE
- ...
J'ai cherché partout dans le repos... rien...
Qui plus est, la libTeleInfo ne peut pas être compatible mode standard. Au moins une ligne renvoyée par le Linky fait plus de 64 caractères (TINFO_BUFSIZE), ...

**Comment by hallard** [comment]
@FredM67 merci de l'info, visiblement j'avais pas pushé le dernier commit, tu peux essayer maintenant ?

**Comment by FredM67** [comment]
Parfait !

**Comment by FredM67** [comment]
Est-ce que tu pourrais stp faire le publish pour platformio? histoire d'avoir accès à cette dernière version ;-)
Merci

**Comment by hallard** [comment]
Heuu je ne sais pas comment on fait et je ne crois pas l'avoir déjà fait en plus.

**Comment by FredM67** [comment]
En fait, ça fonctionne, ça a juste mis un peu de temps...

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________
