### ISSUE TITLE
Erreur compilation LibTeleinfo-1.1.4

### ISSUE THREAD

**Issue by StephaneG38** [hallard/LibTeleinfo#23]
Bonjour,
J'essai de flasher un ESP8266 avec Arduino IDE 1.8.19 mais j'ai cette erreur 
`call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, host, port, uri)
`

Merci par avance pour votre aide
Stéphane

**Comment by StepG38** [comment]
Je viens de trouver la solution en ajoutant : 
![image](https://user-images.githubusercontent.com/38179281/151948928-b7acd087-0649-4073-97ad-8205e783f64a.png)

**Comment by hallard** [comment]
Fixed by #29 thanks for reporting
