### ISSUE TITLE
Echec de compilation Raspberry_JSON

### ISSUE THREAD

**Issue by yetanotherjr** [hallard/LibTeleinfo#25]
Bonjour,

j'essaie de suivre la documentation [Raspberry_JSON](https://github.com/hallard/LibTeleinfo/tree/master/examples/Raspberry_JSON), mais le make échoue:
```text
pi@pizero:~/LibTeleinfo/examples/Raspberry_JSON $ make
cc -DRASPBERRY_PI  -c raspjson.cpp
raspjson.cpp:36:10: fatal error: ../../LibTeleinfo.h: No such file or directory
   36 | #include "../../LibTeleinfo.h"
```
J'ai vu que la structure du dossier a changé (ajout d'un folder `src`), j'ai donc ajusté le fichier cpp et le makefile en conséquence.
La compilation reprend mais échoue plus tard, sur un autre fichier manquant:
```text
pi@pizero:~/LibTeleinfo/examples/Raspberry_JSON $ make
cc -DRASPBERRY_PI  -c ../../src/LibTeleinfo.cpp
../../src/LibTeleinfo.cpp:27:10: fatal error: Arduino.h: No such file or directory
   27 | #include "Arduino.h"
```
Si je tente de commenter, la compilation échoue de nouveau car d'autres fonctions ne sont plus reconnues (`strlcpy`,`strlen_P`,`mktime`)

Pouvez-vous mettre à jour la documentation de l'exemple Raspberry_JSON, afin que la compilation fonctionne avec la structure actuelle du projet ?

EDIT : je viens de voir que la documentation principale indique qu'il faut avoir l'IDE Arduino déjà en place. Pour l'exemple Raspberry_JSON, y a-t-il moyen de faire sans ? Sinon, quelles étapes supplémentaires sont requises ?

Merci !

**Comment by hallard** [comment]
Fixed by #28 thanks for reporting
