### ISSUE TITLE
Probleme PAPP

### ISSUE THREAD

**Issue by dp-site** [hallard/LibTeleinfo#9]
Bonjour,

 je récupère les données (PAPP, IINST et BASE) avec la librairie (beau boulot), le problème c'est qu'après un laps de temps variable, le PAPP passe à des valeurs très élevées.
Je joint un CSV (en .txt Github refuse sinon).
L'erreur se produit ligne 108.
Le debuggage console affiche la même valeur dans  me->value.
Quand j'effectue un reset du 8266 tout redevient normal.
Je n'ai pas de soucis sur BASE et IINST.

[teleinfofeed.csv.txt](https://github.com/hallard/LibTeleinfo/files/338851/teleinfofeed.csv.txt)

**Comment by hallard** [comment]
Should be fixed with latest version
